In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df=pd.read_csv('data.csv')
df.head()

filename  chroma_stft      rmse  spectral_centroid  \
0          a007_20_30.wav     0.694817  0.026579        1364.705872   
1    a014-01-01-10_20.wav     0.741687  0.004577        2277.800541   
2  a014-01-01-160_170.wav     0.703664  0.004202        1986.967460   
3          a014_10_20.wav     0.741687  0.004577        2277.800541   
4        a014_160_170.wav     0.703664  0.004202        1986.967460   

   spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1  \
0         1986.209262  3164.231756            0.035301 -346.429700   
1         2388.947673  4858.834888            0.077501 -431.045631   
2         2302.645593  4531.140505            0.061005 -440.421508   
3         2388.947673  4858.834888            0.077501 -431.045631   
4         2302.645593  4531.140505            0.061005 -440.421508   

        mfcc2      mfcc3  ...     mfcc12    mfcc13    mfcc14    mfcc15  \
0  108.161049  -5.010263  ...   6.863027  6.082835  5.599839 -0.544139   
1   81.188404 -19.983681  ...  10.371519  7.141554  9.786800  1.239608   
2   98.375570 -15.480723  ...   8.353411  6.055960  9.052861 -1.327068   
3   81.188404 -19.983681  ...  10.371519  7.141554  9.786800  1.239608   
4   98.375570 -15.480723  ...   8.353411  6.055960  9.052861 -1.327068   

      mfcc16    mfcc17     mfcc18    mfcc19    mfcc20  label  
0   6.447171  0.107353   5.729503 -1.870822  4.570478  beach  
1  11.921585  0.034888  10.066216  0.181321  8.607600  beach  
2  11.732653 -0.996032   8.226508 -1.967133  6.456439  beach  
3  11.921585  0.034888  10.066216  0.181321  8.607600  beach  
4  11.732653 -0.996032   8.226508 -1.967133  6.456439  beach  

[5 rows x 28 columns]

In [3]:
#dropping unnncessaary
df=df.drop(['filename'],axis=1)
df.head()

chroma_stft      rmse  spectral_centroid  spectral_bandwidth      rolloff  \
0     0.694817  0.026579        1364.705872         1986.209262  3164.231756   
1     0.741687  0.004577        2277.800541         2388.947673  4858.834888   
2     0.703664  0.004202        1986.967460         2302.645593  4531.140505   
3     0.741687  0.004577        2277.800541         2388.947673  4858.834888   
4     0.703664  0.004202        1986.967460         2302.645593  4531.140505   

   zero_crossing_rate       mfcc1       mfcc2      mfcc3      mfcc4  ...  \
0            0.035301 -346.429700  108.161049  -5.010263  54.253111  ...   
1            0.077501 -431.045631   81.188404 -19.983681  40.366436  ...   
2            0.061005 -440.421508   98.375570 -15.480723  40.079875  ...   
3            0.077501 -431.045631   81.188404 -19.983681  40.366436  ...   
4            0.061005 -440.421508   98.375570 -15.480723  40.079875  ...   

      mfcc12    mfcc13    mfcc14    mfcc15     mfcc16    mfcc17     mfcc18  \
0   6.863027  6.082835  5.599839 -0.544139   6.447171  0.107353   5.729503   
1  10.371519  7.141554  9.786800  1.239608  11.921585  0.034888  10.066216   
2   8.353411  6.055960  9.052861 -1.327068  11.732653 -0.996032   8.226508   
3  10.371519  7.141554  9.786800  1.239608  11.921585  0.034888  10.066216   
4   8.353411  6.055960  9.052861 -1.327068  11.732653 -0.996032   8.226508   

     mfcc19    mfcc20  label  
0 -1.870822  4.570478  beach  
1  0.181321  8.607600  beach  
2 -1.967133  6.456439  beach  
3  0.181321  8.607600  beach  
4 -1.967133  6.456439  beach  

[5 rows x 27 columns]

In [4]:
#  creating  label encoding for applying random forest classifier
genre=df.iloc[:,26].values
encoder=LabelEncoder()
df['label']=encoder.fit_transform(genre)
df.head()

chroma_stft      rmse  spectral_centroid  spectral_bandwidth      rolloff  \
0     0.694817  0.026579        1364.705872         1986.209262  3164.231756   
1     0.741687  0.004577        2277.800541         2388.947673  4858.834888   
2     0.703664  0.004202        1986.967460         2302.645593  4531.140505   
3     0.741687  0.004577        2277.800541         2388.947673  4858.834888   
4     0.703664  0.004202        1986.967460         2302.645593  4531.140505   

   zero_crossing_rate       mfcc1       mfcc2      mfcc3      mfcc4  ...  \
0            0.035301 -346.429700  108.161049  -5.010263  54.253111  ...   
1            0.077501 -431.045631   81.188404 -19.983681  40.366436  ...   
2            0.061005 -440.421508   98.375570 -15.480723  40.079875  ...   
3            0.077501 -431.045631   81.188404 -19.983681  40.366436  ...   
4            0.061005 -440.421508   98.375570 -15.480723  40.079875  ...   

      mfcc12    mfcc13    mfcc14    mfcc15     mfcc16    mfcc17     mfcc18  \
0   6.863027  6.082835  5.599839 -0.544139   6.447171  0.107353   5.729503   
1  10.371519  7.141554  9.786800  1.239608  11.921585  0.034888  10.066216   
2   8.353411  6.055960  9.052861 -1.327068  11.732653 -0.996032   8.226508   
3  10.371519  7.141554  9.786800  1.239608  11.921585  0.034888  10.066216   
4   8.353411  6.055960  9.052861 -1.327068  11.732653 -0.996032   8.226508   

     mfcc19    mfcc20  label  
0 -1.870822  4.570478      0  
1  0.181321  8.607600      0  
2 -1.967133  6.456439      0  
3  0.181321  8.607600      0  
4 -1.967133  6.456439      0  

[5 rows x 27 columns]

In [5]:
x=df.iloc[:,0:26]
y=df.iloc[:,26]

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [7]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [10]:
from sklearn.naive_bayes import GaussianNB

In [11]:
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

In [13]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[4 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 5 0 1 0 0 0 0 0 2 0 0 0 1]
 [0 0 2 0 0 0 0 1 0 3 0 0 0 0]
 [0 0 0 5 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 3 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 7 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 8 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 5 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 4 0 2 0 0]
 [0 0 0 0 0 0 0 1 1 1 5 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 3 3 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 1 0 0 0 0 0 0 2 1 0 0 0 6]]
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         6
           1       0.62      0.56      0.59         9
           2       1.00      0.33      0.50         6
           3       0.83      0.83      0.83         6
           4       1.00      0.60      0.75         5
           5       1.00      1.00      1.00         7
           6       1.00      0.80      0.89        10
           7       0.71      1.00      0.83         5
           8       0.20      0.50      0.29         2
           9       0.25 